name: EmployeeService CI/CD to OpenShift

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: self-hosted

    env:
      OPENSHIFT_SERVER: ${{ secrets.OPENSHIFT_SERVER }}
      OPENSHIFT_TOKEN: ${{ secrets.OPENSHIFT_TOKEN }}
      OPENSHIFT_NAMESPACE: ${{ secrets.OPENSHIFT_NAMESPACE }}
      OPENSHIFT_REGISTRY: ${{ secrets.OPENSHIFT_REGISTRY }}

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Set up Java 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn clean package -DskipTests

    - name: Install OpenShift CLI (oc)
      run: |
        curl -LO https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/openshift-client-linux.tar.gz
        tar -xzf openshift-client-linux.tar.gz
        sudo mv oc /usr/local/bin/
        oc version


    - name: Login to OpenShift
      run: |
        echo "OpenShift server is: $OPENSHIFT_SERVER"
        oc login "$OPENSHIFT_SERVER" \
          --token="$OPENSHIFT_TOKEN" \
          --insecure-skip-tls-verify=true
    

    - name: Login to OpenShift Registry
      run: |
        echo $OPENSHIFT_TOKEN | docker login \
          $OPENSHIFT_REGISTRY \
          -u github-actions \
          --password-stdin

    - name: Build Docker Image
      run: |
        docker build -t employee-service:latest .

    - name: Push Image
      run: |
        docker tag employee-service:latest \
          $OPENSHIFT_REGISTRY/$OPENSHIFT_NAMESPACE/employee-service:latest
        docker push \
          $OPENSHIFT_REGISTRY/$OPENSHIFT_NAMESPACE/employee-service:latest

    - name: Deploy to OpenShift
      run: |
        oc apply -f k8s/deployment.yaml
        oc rollout restart deployment employee-service